---
  all:
    hosts:
      sys1: 
        ansible_host: 92.51.167.155 
      web1: 
        ansible_host: 92.51.167.155
    children:
      system:
        hosts:
          sys1:
      web:
        hosts:
          web1:

    