---
  all:
    hosts:
      sys1: 
        ansible_host: lvps92-51-167-155.dedicated.hosteurope.de 
      web1: 
        ansible_host: lvps92-51-167-155.dedicated.hosteurope.de
    children:
      system:
        hosts:
          sys1:
      web:
        hosts:
          web1:

    