---
  all:
    hosts:
      sys1: 
        ansible_host: lvps178-77-98-179.dedicated.hosteurope.de 
      web1: 
        ansible_host: lvps178-77-98-179.dedicated.hosteurope.de
    children:
      system:
        hosts:
          sys1:
      web:
        hosts:
          web1:
      

    