api:
  insecure: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  sample:
    acme:
      email: christian.sterzl@gmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"