---
  - name: Write docker compose file
    template:
      src: docker-compose_yml.j2
      dest: "{{ docker_base_path }}/docker-compose_pwas.yml"
      mode: 0644
      backup: yes
#  - name: Load and start docker pwas
#    include_tasks: load_docker.yml
#    vars:
#      pwa: "{{ item }}"
#    with_dict: "{{ pwas }}"
  - name: Create data dirs
    file:
      path: "{{ docker.paths.data }}{{ item }}"
      state: directory
    loop:
      - "labelsbe"
      - "labelsbedev"
      - "cryptoreport"
  - name: Create update crypt file
    template:
      src: update_crypto.j2.sh
      dest: "{{ docker_base_path }}/update_crypto.sh"
      mode: 0755
      backup: yes
  - name: Add cronjob for update_crypto job
    cron:
      name: "update crypto data"
      special_time: hourly
      user: "{{ ansible_user }}"
      backup: yes
      job: "{{ docker_base_path }}/update_crypto.sh"    