---
  - name: Load and start docker pwas
    include_tasks: load_docker.yml
    vars:
      pwa: "{{ item }}"
    with_dict: "{{ pwas }}"
  #- name: debug
  #  include_tasks: debug_test.yml
  #  vars:
  #    pwa: "{{ item }}"
  #  with_dict: "{{ pwas }}"