---
- debug:
    msg: "Start container. Restart: {{ restart }}"
- name: Create container label KV-pairs
  set_fact:
    container_label_keyvalue_pairs:
      - key: "traefik.enable"
        value: "true"
      - key: "traefik.http.routers.{{ pwa.value.name }}.entrypoints"
        value: "web"
      - key: "traefik.http.routers.{{ pwa.value.name }}.entrypoints"
        value: "web"
      - key: "traefik.http.routers.{{ pwa.value.name }}.rule"
        value: "Host(`{{ pwa.value.host }}`)"
      - key: "traefik.http.middlewares.{{ pwa.value.name }}-https-redirect.redirectscheme.scheme"
        value: "https"
      - key: "traefik.http.routers.{{ pwa.value.name }}.middlewares"
        value: "{{ pwa.value.name }}-https-redirect"
      - key: "traefik.http.routers.{{ pwa.value.name }}-secure.entrypoints"
        value: "websecure"
      - key: "traefik.http.routers.{{ pwa.value.name }}-secure.rule"
        value: "Host(`{{ pwa.value.host }}`)"
      - key: "traefik.http.routers.{{ pwa.value.name }}-secure.tls"
        value: "true"
      - key: "traefik.http.routers.{{ pwa.value.name }}-secure.tls.certresolver"
        value: "myresolver"
      - key: "traefik.domain"
        value: "{{ pwa.value.host }}"
      - key: "traefik.docker.network"
        value: "web_proxy"
- name: Set dictionary
  set_fact:
    container_labels: "{{ container_labels|default({}) | combine( {label_item.key: label_item.value} ) }}"
  with_items:
    - "{{ container_label_keyvalue_pairs }}"
  loop_control:
    loop_var: label_item
- name: Start container
  docker_container:
    name: "{{ pwa.value.name }}"
    image: "{{ pwa.value.image_name }}"
    state: started
    restart: "{{ restart }}"
    networks_cli_compatible: no
    networks:
      - name: web_proxy
    ports:
      - "{{ pwa.value.ports.exposed }}:{{ pwa.value.ports.listen }}"
    labels: "{{ container_labels }}"
  become: yes