log:
  filePath: "/var/log/traefik/traefik.log"
  #format: json
  level: DEBUG

accessLog:
  filePath: "/var/log/traefik/access.log"
  #format: json

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: christian.sterzl@gmail.com
      storage: /etc/traefik/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

tls:
  stores:
    default: {}

providers:
  docker:
    exposedByDefault: true
    endpoint: "unix:///var/run/docker.sock"