---
  - name: Create directory
    file:
      path: web/
      state: directory
  - name: Create config dirs
    file:
      path: "{{ docker.paths.configs }}{{ item }}"
      state: directory
    loop: "{{ web_containers }}"
  - name: Create work dirs
    file:
      path: "{{ docker.paths.work }}{{ item }}"
      state: directory
    loop: "{{ web_containers }}"
  - name: Create log dirs
    file:
      path: "{{ docker.paths.logs }}{{ item }}"
      state: directory
    loop: "{{ web_containers }}"
  - name: Create data dirs
    file:
      path: "{{ docker.paths.data }}{{ item }}"
      state: directory
    loop: "{{ web_containers }}"
  - name: Run web container specific tasks
    include_tasks: "{{ item }}.yml"
    loop: "{{ web_containers }}"
  - name: Write docker compose file
    template:
      src: docker-compose_yml.j2
      dest: "{{ docker_base_path }}/docker-compose.yml"
      mode: 0644
      backup: yes
  - name: Create restart script
    template:
      src: start_sh.j2.sh
      dest: "{{ docker_base_path }}/start.sh"
      mode: 0755
      backup: yes
  - name: Add cronjob to restart docker if neccessary
    cron:
      name: "check docker containers"
      minute: "*/5"
      user: "{{ ansible_user }}"
      backup: yes
      job: "{{ docker_base_path }}/start.sh"
  - name: Run docker-compose
    block:
      - name: Find docker compose files
        find:
          paths: "{{ docker_base_path }}"
          patterns: 'docker-compose*.yml'
          recurse: no
        register: compose_files
      - docker_compose:
          project_src: "{{ docker_base_path }}"
          state: present
          restarted: "{{ restart_container }}"
          files: "{{ compose_files.files | map(attribute='path') | list }}"
        register: compose_output
      - debug:
          var: compose_output