---
  - name: Create directory
    file:
      path: web/
      state: directory
  - name: Sync directories
    synchronize:
      src: .
      dest: web/
      delete: yes
      recursive: yes
    register: output
  - debug:
      var: output
  - name: Create log dirs
    file:
      path: "{{ docker_logpath }}/{{ item }}"
      state: directory
    loop: "{{ web_containers }}"
  - name: Run docker-compose
    block:
      - docker_compose:
          project_src: web/
          state: present
          restarted: yes
        register: compose_output
      - debug:
          var: compose_output
    when: output.msg != ""