---
  - name: Pgadmin - Write default_password secret
    copy:
      content: "{{ vault_pgadmin_default_password }}"
      dest: "{{ docker_base_path }}/secrets/pgadmin_default_password"
      mode: '0644'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: Pgadmin - Change permissions for data dir
    file:
      path: "{{ docker.paths.data }}pgadmin"
      owner: "5050"
      group: "5050"
      mode: 0755
    become: yes