---
  - name: PhotoPrism - Write db_password secret
    copy:
      content: "{{ vault_photoprism_db_password }}"
      dest: "{{ docker_base_path }}/secrets/photoprism_db_password"
      mode: '0644'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: PhotoPrism - Write db_root_password secret
    copy:
      content: "{{ vault_photoprism_db_root_password }}"
      dest: "{{ docker_base_path }}/secrets/photoprism_db_root_password"
      mode: '0644'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: PhotoPrism - Create originals directory
    file:
      path: "{{ docker.paths.work }}photoprism/originals"
      state: directory
      mode: '0755'
  - name: PhotoPrism - Create import directory
    file:
      path: "{{ docker.paths.work }}photoprism/import"
      state: directory
      mode: '0755'
  - name: PhotoPrism - Create storage directory
    file:
      path: "{{ docker.paths.data }}photoprism/storage"
      state: directory
      mode: '0755'
  - name: PhotoPrism - Create database directory
    file:
      path: "{{ docker.paths.data }}photoprism/database"
      state: directory
      mode: '0755'
  - name: PhotoPrism - Deploy seccomp profile
    template:
      src: photoprism/seccomp_json.j2
      dest: "{{ docker.paths.configs }}photoprism/seccomp.json"
      mode: '0644'