---
  - name: Portus - Copy key file
    copy:
      src: "portus/portus.key"
      dest: "{{ docker.paths.configs }}portus/portus.key"
      force: yes
  - name: Portus - Write configuration
    template:
      src: portus/portus_yml.j2
      dest: "{{ docker.paths.configs }}portus/config.yml"
      mode: 0644
      backup: yes
  - name: Portus - Check if pgdata exists
    stat: 
      path: "{{ docker.paths.data }}portus/pgdata"
    register: pgdata_dir
  - name: Portus - Create pgdata
    file:
      path: "{{ docker.paths.data }}portus/pgdata"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    when: pgdata_dir.stat.exists == False