---
  - name: Registry - Write configuration
    template:
      src: registry/registry_yml.j2
      dest: "{{ docker.paths.configs }}registry/config.yml"
      mode: 0644
      backup: yes
  - name: Registry - Create secrets dir
    file:
      path: "{{ docker.paths.configs }}registry/secrets"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: Registry - Setup garbage collection cron
    cron:
      name: "Registry garbage collection"
      minute: "0"
      hour: "3"
      job: "docker exec web_registry bin/registry garbage-collect /etc/docker/registry/config.yml --delete-untagged 2>&1 | logger -t registry-gc"
      user: "{{ ansible_user }}"