---
  pwas:
    paint:
      tar_gz: paint_latest.tar.gz
      tar: paint_latest.tar
      name: paint
      image_name: waxolunist/paint
      host: paint.{{ topleveldomain }}
      ports:
        listen: 8002
        exposed: 8000
  
  restart_container: no