---
  pwas:
    paint:
      tar_gz: paint_latest.tar.gz
      tar: paint_latest.tar
      name: paint
      image_name: waxolunist/paint
      host: paint.{{ topleveldomain }}
      ports:
        listen: 8002
        exposed: 8000
  paint2:
    domain: "paint.{{ topleveldomain }}"
    port: 8043
  paint2dev:
    domain: "paint-dev.{{ topleveldomain }}"
    port: 8043
#  releasemanager:
#    domain: "releasemanager.{{ topleveldomain }}"
#    port: 3000
#  releasemanagerdev:
#    domain: "releasemanager-dev.{{ topleveldomain }}"
#    port: 3000
  labelsbe:
    domain: "labels.{{ topleveldomain }}"
    port: 3000
  labelsbedev:
    domain: "labels-dev.{{ topleveldomain }}"
    port: 3000
  cryptocurrency:
    domain: "crypto.{{ topleveldomain }}"
    port: 6150
  restart_container: no