---
  pwas:
    paint:
      tar_gz: paint_latest.tar.gz
      tar: paint_latest.tar
      name: paint
      image_name: waxolunist/paint
      host: paint.{{ topleveldomain }}
      ports:
        listen: 8002
        exposed: 8000
  paint2:
    domain: "paint.{{ topleveldomain }}"
    port: 8043
  paint2dev:
    domain: "paint-dev.{{ topleveldomain }}"
    port: 8043
  restart_container: no